# Generated by Django 4.1.1 on 2022-10-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0006_alter_dosen_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosen',
            name='kelompok_id',
        ),
        migrations.DeleteModel(
            name='Kelompok',
        ),
    ]
