# Generated by Django 4.1.1 on 2022-10-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0008_alter_dosen_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='foto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
