# Generated by Django 4.1.1 on 2022-10-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staf',
            name='nama',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staf',
            name='jabatan',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='staf',
            name='nip',
            field=models.CharField(max_length=40),
        ),
    ]
