# Generated by Django 4.1.1 on 2022-10-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staf', '0002_staf_nama_alter_staf_jabatan_alter_staf_nip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staf',
            name='jabatan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
