# Generated by Django 4.1.1 on 2022-10-05 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=9)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=70)),
                ('tempattanggallahir', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=150)),
                ('kelompok_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mahasiswa.kelompok')),
            ],
        ),
    ]
