# Generated by Django 4.1.1 on 2022-10-05 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dosen',
            new_name='Mahasiswa',
        ),
    ]
