# Generated by Django 4.1.1 on 2022-10-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_rename_dosen_mahasiswa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahasiswa',
            name='kelompok_id',
        ),
        migrations.DeleteModel(
            name='Kelompok',
        ),
    ]
