# Generated by Django 4.1.1 on 2022-10-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0003_remove_mahasiswa_kelompok_id_delete_kelompok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahasiswa',
            name='tempattanggallahir',
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='ttl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
