# Generated by Django 4.1.1 on 2022-10-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0004_remove_mahasiswa_tempattanggallahir_mahasiswa_ttl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
